[tools]
go = "1.25.8"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"go:github.com/kisielk/errcheck" = "latest"
golangci-lint = "latest"
mockery = "latest"
swag = "latest"

"pre-commit" = "latest"

"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
