// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rest

import (
	"github.com/haipham22/govern/http"
	"github.com/labstack/echo/v4"
	"go.uber.org/zap"
	"golang-sample/internal/handler/rest/controllers/auth"
	"golang-sample/internal/handler/rest/controllers/health"
	auth2 "golang-sample/internal/service/auth"
	"golang-sample/internal/storage/user"
	"golang-sample/pkg/config"
	"golang-sample/pkg/postgres"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// New creates a new Handler with all dependencies wired.
// Returns: server, cleanup function, error
func New(log *zap.SugaredLogger, port int64, appConfig *config.EnvConfigMap) (http.Server, func(), error) {
	echoEcho := echo.New()
	db, cleanup, err := provideDB(appConfig)
	if err != nil {
		return nil, nil, err
	}
	storage := user.New(log, db)
	restAuthConfig := provideAuthConfig(appConfig)
	service := provideAuthService(log, storage, restAuthConfig)
	controller := auth.New(service)
	healthController := health.New(db)
	bool2 := provideDebugFlag(appConfig)
	string2 := provideEnv(appConfig)
	server := NewHandler(log, echoEcho, controller, healthController, port, bool2, string2)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

// authConfig holds JWT configuration
type authConfig struct {
	jwtSecret string
}

func provideAuthService(
	log *zap.SugaredLogger,
	storage user.Storage,
	cfg authConfig,
) auth2.Service {
	jwtExpiration := 72 * time.Hour
	return auth2.NewAuthService(log, storage, cfg.jwtSecret, jwtExpiration)
}

func provideDebugFlag(appConfig *config.EnvConfigMap) bool {
	return appConfig.App.Debug
}

func provideEnv(appConfig *config.EnvConfigMap) string {
	return appConfig.App.Env
}

func provideDB(appConfig *config.EnvConfigMap) (*gorm.DB, func(), error) {
	return postgres.NewGormDB(appConfig.Postgres.DSN)
}

// provideAuthConfig extracts JWT config from main config
func provideAuthConfig(appConfig *config.EnvConfigMap) authConfig {
	return authConfig{
		jwtSecret: appConfig.API.Secret,
	}
}
