// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/haipham22/golang-sample/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CheckUniqueness provides a mock function for the type MockStorage
func (_mock *MockStorage) CheckUniqueness(ctx context.Context, username string, email string) (bool, bool, error) {
	ret := _mock.Called(ctx, username, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckUniqueness")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, bool, error)); ok {
		return returnFunc(ctx, username, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, username, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = returnFunc(ctx, username, email)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, username, email)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_CheckUniqueness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUniqueness'
type MockStorage_CheckUniqueness_Call struct {
	*mock.Call
}

// CheckUniqueness is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
func (_e *MockStorage_Expecter) CheckUniqueness(ctx any, username any, email any) *MockStorage_CheckUniqueness_Call {
	return &MockStorage_CheckUniqueness_Call{Call: _e.mock.On("CheckUniqueness", ctx, username, email)}
}

func (_c *MockStorage_CheckUniqueness_Call) Run(run func(ctx context.Context, username string, email string)) *MockStorage_CheckUniqueness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CheckUniqueness_Call) Return(b bool, b1 bool, err error) *MockStorage_CheckUniqueness_Call {
	_c.Call.Return(b, b1, err)
	return _c
}

func (_c *MockStorage_CheckUniqueness_Call) RunAndReturn(run func(ctx context.Context, username string, email string) (bool, bool, error)) *MockStorage_CheckUniqueness_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithPassword provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateUserWithPassword(ctx context.Context, user *domain.User, passwordHash string) (*domain.User, error) {
	ret := _mock.Called(ctx, user, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithPassword")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User, string) (*domain.User, error)); ok {
		return returnFunc(ctx, user, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User, string) *domain.User); ok {
		r0 = returnFunc(ctx, user, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User, string) error); ok {
		r1 = returnFunc(ctx, user, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateUserWithPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithPassword'
type MockStorage_CreateUserWithPassword_Call struct {
	*mock.Call
}

// CreateUserWithPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - passwordHash string
func (_e *MockStorage_Expecter) CreateUserWithPassword(ctx any, user any, passwordHash any) *MockStorage_CreateUserWithPassword_Call {
	return &MockStorage_CreateUserWithPassword_Call{Call: _e.mock.On("CreateUserWithPassword", ctx, user, passwordHash)}
}

func (_c *MockStorage_CreateUserWithPassword_Call) Run(run func(ctx context.Context, user *domain.User, passwordHash string)) *MockStorage_CreateUserWithPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CreateUserWithPassword_Call) Return(user1 *domain.User, err error) *MockStorage_CreateUserWithPassword_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockStorage_CreateUserWithPassword_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, passwordHash string) (*domain.User, error)) *MockStorage_CreateUserWithPassword_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type MockStorage
func (_mock *MockStorage) FindUserByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockStorage_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockStorage_Expecter) FindUserByUsername(ctx any, username any) *MockStorage_FindUserByUsername_Call {
	return &MockStorage_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *MockStorage_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockStorage_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_FindUserByUsername_Call) Return(user *domain.User, err error) *MockStorage_FindUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStorage_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockStorage_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsernameWithPassword provides a mock function for the type MockStorage
func (_mock *MockStorage) FindUserByUsernameWithPassword(ctx context.Context, username string) (*domain.User, string, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsernameWithPassword")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, string, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, username)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_FindUserByUsernameWithPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsernameWithPassword'
type MockStorage_FindUserByUsernameWithPassword_Call struct {
	*mock.Call
}

// FindUserByUsernameWithPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockStorage_Expecter) FindUserByUsernameWithPassword(ctx any, username any) *MockStorage_FindUserByUsernameWithPassword_Call {
	return &MockStorage_FindUserByUsernameWithPassword_Call{Call: _e.mock.On("FindUserByUsernameWithPassword", ctx, username)}
}

func (_c *MockStorage_FindUserByUsernameWithPassword_Call) Run(run func(ctx context.Context, username string)) *MockStorage_FindUserByUsernameWithPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_FindUserByUsernameWithPassword_Call) Return(user *domain.User, passwordHash string, err error) *MockStorage_FindUserByUsernameWithPassword_Call {
	_c.Call.Return(user, passwordHash, err)
	return _c
}

func (_c *MockStorage_FindUserByUsernameWithPassword_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, string, error)) *MockStorage_FindUserByUsernameWithPassword_Call {
	_c.Call.Return(run)
	return _c
}

// IsExistBy provides a mock function for the type MockStorage
func (_mock *MockStorage) IsExistBy(ctx context.Context, field string, condition string) (bool, error) {
	ret := _mock.Called(ctx, field, condition)

	if len(ret) == 0 {
		panic("no return value specified for IsExistBy")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, field, condition)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, field, condition)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, field, condition)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_IsExistBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExistBy'
type MockStorage_IsExistBy_Call struct {
	*mock.Call
}

// IsExistBy is a helper method to define mock.On call
//   - ctx context.Context
//   - field string
//   - condition string
func (_e *MockStorage_Expecter) IsExistBy(ctx any, field any, condition any) *MockStorage_IsExistBy_Call {
	return &MockStorage_IsExistBy_Call{Call: _e.mock.On("IsExistBy", ctx, field, condition)}
}

func (_c *MockStorage_IsExistBy_Call) Run(run func(ctx context.Context, field string, condition string)) *MockStorage_IsExistBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_IsExistBy_Call) Return(b bool, err error) *MockStorage_IsExistBy_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorage_IsExistBy_Call) RunAndReturn(run func(ctx context.Context, field string, condition string) (bool, error)) *MockStorage_IsExistBy_Call {
	_c.Call.Return(run)
	return _c
}
