// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/labstack/echo/v4"
	"go.uber.org/zap"
	"golang-sample/internal/handler/rest/auth"
	"golang-sample/internal/handler/rest/health"
	"golang-sample/internal/storage"
	"golang-sample/pkg/postgres"
)

// Injectors from wire.go:

func New(dbDSN string, log *zap.SugaredLogger) (*Handler, func(), error) {
	echoEcho := echo.New()
	db, cleanup, err := postgres.NewGormDB(dbDSN)
	if err != nil {
		return nil, nil, err
	}
	storageStorage := storage.NewStorage(log, db)
	authController := auth.NewAuthController(log, storageStorage)
	healthController := health.NewController(db)
	handler := NewHandler(log, echoEcho, authController, healthController)
	return handler, func() {
		cleanup()
	}, nil
}
